#!/bin/bash
#BSUB -J bf_wider_C
#BSUB -q short
#BSUB -n 4
#BSUB -R "rusage[mem=8000]"
#BSUB -o /home/labs/ginossar/talfis/LiveImaging/BrightFieldEmbedding/logs/bf_wider_C_%J.out
#BSUB -e /home/labs/ginossar/talfis/LiveImaging/BrightFieldEmbedding/logs/bf_wider_C_%J.err

source /home/labs/ginossar/talfis/envs/cellpose_embed/bin/activate

python /home/labs/ginossar/talfis/LiveImaging/BrightFieldEmbedding/10_tabular_cls_wider_C.py
