#!/bin/bash
#BSUB -J bf_reg_g2r
#BSUB -q short
#BSUB -n 4
#BSUB -R "rusage[mem=8192]"
#BSUB -W 1:00
#BSUB -o /home/labs/ginossar/talfis/LiveImaging/logs/bf_reg_g2r_%J.out
#BSUB -e /home/labs/ginossar/talfis/LiveImaging/logs/bf_reg_g2r_%J.err

echo "Job started : $(date)"
echo "Host        : $(hostname)"

python3 /home/labs/ginossar/talfis/LiveImaging/BrightFieldEmbedding/06_bf_regression_g2r.py

echo "Job finished: $(date)"
