#!/bin/bash
#BSUB -J bf_comparison
#BSUB -q short
#BSUB -n 4
#BSUB -R "rusage[mem=8192]"
#BSUB -W 2:00
#BSUB -o /home/labs/ginossar/talfis/LiveImaging/logs/bf_comparison_%J.out
#BSUB -e /home/labs/ginossar/talfis/LiveImaging/logs/bf_comparison_%J.err

echo "Job started : $(date)"
echo "Host        : $(hostname)"

python3 /home/labs/ginossar/talfis/LiveImaging/BrightFieldEmbedding/05_bf_comparison_figure.py

echo "Job finished: $(date)"
