#!/bin/bash
#BSUB -J bf_mock_othercell
#BSUB -q short-gpu
#BSUB -n 2
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -R "rusage[mem=16000]"
#BSUB -o /home/labs/ginossar/talfis/LiveImaging/mock_embedding/logs/bf_mock_othercell_%J.out
#BSUB -e /home/labs/ginossar/talfis/LiveImaging/mock_embedding/logs/bf_mock_othercell_%J.err

source /home/labs/ginossar/talfis/envs/cellpose_embed/bin/activate

python /home/labs/ginossar/talfis/LiveImaging/mock_embedding/02b_bf_mock_othercell.py
