#!/bin/bash
#BSUB -J gfp_mock_extract
#BSUB -q short-gpu
#BSUB -n 2
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -R "rusage[mem=16000]"
#BSUB -o /home/labs/ginossar/talfis/LiveImaging/mock_embedding/logs/gfp_mock_extract_%J.out
#BSUB -e /home/labs/ginossar/talfis/LiveImaging/mock_embedding/logs/gfp_mock_extract_%J.err

source /home/labs/ginossar/talfis/envs/cellpose_embed/bin/activate

python /home/labs/ginossar/talfis/LiveImaging/mock_embedding/01_gfp_mock_extract.py
